### ISSUE TITLE
Obtener el documento PDF de imágenes en tiempo real

### ISSUE THREAD

**Issue by jchabledev** [jchabledev/MagicMirror#1]
**Issue:**
Falla la lectura del archivo PDF de las imágenes al iniciar la impresión.

---
**Fix:**
Esto se debe a que el documento PDF en ciertas ocasiones se demora en convertir las imágenes, así que para evitar esto es necesario crear una función que detecte la existencia del documento en la carpeta del evento y de ser así active la función de imprimir.
Leer los contenidos de un archivo en la memoria es una tarea de programación muy común y, como ocurre con muchas otras cosas, la API central de Node.js proporciona métodos para hacer que esto sea trivial. Hay una variedad de métodos de sistema de archivos, todos contenidos en el **módulo fs**. La forma más fácil de leer todo el contenido de un archivo es con **fs.readFile**, de la siguiente manera:

```
fs = require('fs');
fs.readFile(file, [encoding], [callback]);

```
- **File** = (string) filepath del archivo para leer

- **Encouding:**  es un parámetro opcional que especifica el tipo de codificación para leer el archivo. Las posibles codificaciones son 'ascii', 'utf8' y 'base64'. Si no se proporciona ninguna codificación, el valor predeterminado es utf8.

- **Callback:** es una función para llamar cuando se ha leído el archivo y el contenido está listo; se pasan dos argumentos, error y datos. Si no hay ningún error, el error será nulo y los datos contendrán los contenidos del archivo; de lo contrario, error contiene el mensaje de error.

---
**Afectados:**
Al finalizar la creación del documento PDF se ejecuta la siguiente función:

```
function leerArchivoPDF(_ruta) {
  var id = setInterval(getPDF,1000);
  function getPDF() {
          var imagenes={
            rImagen : _ruta,
          };
          // DO POST
          $.ajax({
          type : "POST",
          contentType : "application/json",
          url : "/readpdfimagefile",
          data : JSON.stringify(imagenes),
          dataType : 'json',
          success : function(data) {
            if (data == "1") {
              var contenido = getId('to-pdf');
              var test="impresion";
              var galeria = contenido.innerHTML;
              var evento = getId('eventName').value;
              imprimirFotosAuto(evento,test);
              clearInterval(id);
            }
            //console.log("Post Successfully! " + JSON.stringify(data));
          },
          error : function(e) {
            //alert("Error Creating PDF Imagenes! "+e);
            console.log("ERROR WHILE READING PDF: ", e);
          }
          });
 }
}

```
>>Esta función se ejecuta cada segundo, si detecta que el archivo ya existe **(recibe 1)**, ejecuta la función para imprimir el archivo pasandole los parámetros **(ruta, nombre)** y cancelando el contador con **clearInterval()** . 

La ruta que procesa esta funcion es la siguiente:

```
  //Verifica que se haya creado el PDF
    app.post('/readpdfimagefile', function (req, res) {
          // string generated by canvas.toDataURL()
          var evento=req.body.nEvento; //Nombre evento
          var pdfDir="./client/assets/img/"+evento+"/"+evento+"_impresion.pdf"; //Directorio completo

          fs.readFile(pdfDir, 'utf8', function (err,data) {
            if (err) {
              return res.json(err);
            }
            else {
               res.json("1");
            }
            //console.log(data);
          });
    });

```

---
**Ejemplo:**

Veamos ahora un ejemplo de lo que sucede cuando intentas leer un archivo no válido: el ejemplo más fácil es el que no existe.

```
fs = require('fs');
fs.readFile('/doesnt/exist', 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  console.log(data);
});


```
Esta es la Salida (Output):

```
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'ENOENT, No such file or directory \'/doesnt/exist\'',
  errno: 2,
  code: 'ENOENT',
  path: '/doesnt/exist' }

```

>>De esta forma podemos detectar si existe o no el archivo PDF especificado.

---

**Backup:**
Ruta: `C:\Users\desarrollo\Documents\Desarrollo\MagicMirror\`

---
**Deploy:**
Fecha:  03/06/2018

**Comment by rsanchezdev** [comment]
Excelente
